config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: 'about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  #has_one_attached :book
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  #def get_profile_image(width, height)
    #unless profile_image.attached?
      #file_path = Rails.root.join('app/assets/images/no_image_sample.jpg')
      #profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    #end
      #profile_image.variant(resize_to_limit: [width, height]).processed
  #end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit, :update]

  def new
    @book = Book.new
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice]="You have creatad book successfully."
       redirect_to book_path(@book)
    else
       @user = current_user
       @books = Book.all
       render :index
    end
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
       flash[:notice]="Book was successfully destroyed."
       redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
     redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
          <% if @book.errors.any? %>
            <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>

          <%= form_with model: @book do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <!--<input class="form-control book_title" type="text" name="book[title]" id="book_title">-->
              <%= f.text_field :title, class: "form-control book_title", autofocus: true, id:"book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <!--<textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>-->
              <%= f.text_area:body, class: "form-control book_body", autofocus: true, id:"book_body" %>
            </div>
            <div class="form-group">
                <%= f.submit 'Update Book',class: "btn btn-success" %>
            </div>
            <% end %>
            <div class="menu">
              <%= link_to "Show", book_path(@book) %>
              |
              <%= link_to "Back", books_path %>
            </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
    <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
<% end %>

<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image(100,100) %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
            </tbody>
          </table>

          <div class="row">
            <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
            <% end %>
          </div>

          <h2 class="mt-3">New book</h2>
            <%= form_with model: @book do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <P><%= f.text_field :title, size: 30 %></P>
            </div>

            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <p><%= f.text_area :body, size: "30×30" %></p>
            </div>
            <div class="form-group">
              <%= f.submit 'Create Book',class: "btn btn-success" %>
            </div>
            <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Title</th>
              <th scope="col">Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(80,80) %>
                  <% end %>
                </td>
                <td><%=link_to book.title, book_path(book.id)%></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<h1>New book</h1>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
<% if @book.errors.any? %>
    <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
<% end %>

<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image(100,100) %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
            </tbody>
          </table>

          <div class="row">
            <%# if @user == current_user %>
            <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
            <% end %>
            <%# end %>
          </div>

          <h2 class="mt-3">New book</h2>
            <%= form_with model: @book do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <P><%= f.text_field :title, size: 30 %></P>
            </div>

            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <p><%= f.text_area :body, size: "30×30" %></p>
            </div>
            <div class="form-group">
              <%= f.submit 'Create Book',class: "btn btn-success" %>
            </div>
            <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>

              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= image_tag @user.get_profile_image(80,80) %>
                <% end %></br>
                  <%= link_to @user.name, user_path(@user) %>
              </td>

              <td><%= link_to @books.title, book_path(@books) %></td>
              <td><%= @books.body %></td>
              <% if @books.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@books), class:"btn btn-success"%></td>
              <td><%= link_to "Destroy", book_path(@books), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</main>